### ISSUE TITLE
Chrome drive error 

### ISSUE THREAD

**Issue by ghost** [kamalkhan/web-browser#1]
Can i know what's the issue ?

Here the error log
`Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: was killed. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location C:\laragon\www\js\vendor\bhittani\web-driver\drivers\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) in C:\laragon\www\js\vendor\php-webdriver\webdriver\lib\Exception\WebDriverException.php:139 Stack trace: #0 C:\laragon\www\js\vendor\php-webdriver\webdriver\lib\Remote\HttpCommandExecutor.php(371): Facebook\WebDriver\Exception\WebDriverException::throwException('unknown error', 'unknown error: ...', Array) #1 C:\laragon\www\js\vendor\php-webdriver\webdriver\lib\Remote\RemoteWebDriver.php(135): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 C:\laragon\www\js\vendor\bhittani\web-driver\src\Maker.php(61): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\R in C:\laragon\www\js\vendor\bhittani\web-driver\src\Maker.php on line 85`

**Comment by kamalkhan** [comment]
Please use the [issue template](https://github.com/kamalkhan/web-browser/blob/master/.github/ISSUE_TEMPLATE.md) to report issues.

Note: This package is still in development.

As far as your issue with the chrome driver, try using the phantomjs driver and let me know if that works.

**Comment by ghost** [comment]
Phantomjs working well, only chrome error getting

**Comment by kamalkhan** [comment]
Do you have a chrome browser installed on your OS? The chrome driver requires a chrome browser installation.

**Comment by ghost** [comment]
Yes, iam using another framework https://github.com/chrome-php/chrome and
it working well

**Comment by ghost** [comment]
Here the bin path of both drivers
Chrome
http://3.134.82.150/web/vendor/bhittani/web-driver/drivers/chrome.exe
Phantomjs
http://3.134.82.150/web/vendor/bhittani/web-driver/drivers/phantomjs.exe

**Comment by kamalkhan** [comment]
This might be an issue with the background process being used.

I will try to debug this when I start working on it.

**Comment by ghost** [comment]
Ok, thanks.
